apiVersion: apps/v1
kind: Deployment
metadata:
  name: lb
  labels:
    app: lb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lb
  template:
    metadata:
      labels:
        app: lb
    spec:
      containers:
      - name: lb
        image: nginx:1.14.2
        ports:
        - containerPort: 80
