apiVersion: apps/v1
kind: Deployment
metadata:
  name: cmg-deployment
  labels:
    app: mg
spec:
  replicas: 8
  selector:
    matchLabels:
      app: mg
  template:
    metadata:
      labels:
        app: mg
    spec:
      containers:
      - name: mg
        image: nginx:1.14.2
        ports:
        - containerPort: 80
