apiVersion: v1
kind: Pod
metadata:
  name: csf
  labels:
    app.kubernetes.io/name: proxy
spec:
  containers:
  - name: mg
    image: nginx:stable
    ports:
      - containerPort: 80
        name: http-web-svc
